### ISSUE TITLE
Conditional Compilation of Logger Package

### ISSUE THREAD

**Issue by PhilippDahlem** [mt-ag/quasto#14]
the following steps are needed to ensure a clean installation that is not dependent on a compiled logger package:

1. add a parameter to the installer that asks if the logger package is  installed
2.
Option 1:
add a dynamic package header filled with a constant set to the installer parameter (logger_installed constant number = 0;)

Option 2: 
Staticly set the compiler flag in order to prevent the wrapper to be compiled when the logger package does not exists
to tell the oracle compiler if the following code is to be compiled

3. create a wrapper function that calls the logger package and define with the compiler notation dynamic Compilerflag in order 
currently we concluded that the first option to create a header package that is created in the installation process fits our development process the best

**Comment by OliverLemm** [comment]
we need these attributes

- version
- utplsql_installed
- logger_installed
- apex_installed
