### ISSUE TITLE
add "INFO:","WARNING:" and "ERROR:" to installation-scripts

### ISSUE THREAD

**Issue by PhilippDahlem** [mt-ag/quasto#21]
Every Script executes two times a "select count on user_objects" to determine if the object already exists.
One time before the execution of the database-action and one time after.
For each case of status we have **3** diffrent Jenkins-Tags:

1. INFO:    everything went alright => green => nothing needs to be checked
2. WARNING: the object in most cases already exists  => yellow => you should take a look what already exists (sometimes its alright when the job runs multiple times , its normal when you install multiple times that the job will turn yelllow)
3. ERROR: the object couldnt be created => red => the script needs to be corrected

In this ticket we need to add those tags to all of our install scripts

Also to remind we should check the type install scripts for the force keywords.
Types with table dependencies cannot be forced and dont need the keyword

**Comment by semihBozok** [comment]
Added Jenkins Tag to all Scripts
